steps:
  - label: ":pipeline: Pipeline upload"
    command: buildkite-agent pipeline upload .buildkite/pipeline_alpha.yml
    if: build.env("WORKFLOW") == "ALPHA"
  - label: ":pipeline: Pipeline upload"
    command: buildkite-agent pipeline upload .buildkite/pipeline_beta.yml
    if: build.env("WORKFLOW") == "BETA"
  - label: ":pipeline: Pipeline upload"
    command: buildkite-agent pipeline upload .buildkite/real_pipeline.yml
    if: build.env("WORKFLOW") == null
